In [63]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import matplotlib.pyplot as plt

In [51]:
#csv파일 불러오기
diabetes = pd.read_csv("diabetes.csv")
diabetes

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [52]:
#상관관계 분석
diabetes.corr()

Pregnancies   Glucose  BloodPressure  SkinThickness  \
Pregnancies                  1.000000  0.129459       0.141282      -0.081672   
Glucose                      0.129459  1.000000       0.152590       0.057328   
BloodPressure                0.141282  0.152590       1.000000       0.207371   
SkinThickness               -0.081672  0.057328       0.207371       1.000000   
Insulin                     -0.073535  0.331357       0.088933       0.436783   
BMI                          0.017683  0.221071       0.281805       0.392573   
DiabetesPedigreeFunction    -0.033523  0.137337       0.041265       0.183928   
Age                          0.544341  0.263514       0.239528      -0.113970   
Outcome                      0.221898  0.466581       0.065068       0.074752   

                           Insulin       BMI  DiabetesPedigreeFunction  \
Pregnancies              -0.073535  0.017683                 -0.033523   
Glucose                   0.331357  0.221071                  0.137337   
BloodPressure             0.088933  0.281805                  0.041265   
SkinThickness             0.436783  0.392573                  0.183928   
Insulin                   1.000000  0.197859                  0.185071   
BMI                       0.197859  1.000000                  0.140647   
DiabetesPedigreeFunction  0.185071  0.140647                  1.000000   
Age                      -0.042163  0.036242                  0.033561   
Outcome                   0.130548  0.292695                  0.173844   

                               Age   Outcome  
Pregnancies               0.544341  0.221898  
Glucose                   0.263514  0.466581  
BloodPressure             0.239528  0.065068  
SkinThickness            -0.113970  0.074752  
Insulin                  -0.042163  0.130548  
BMI                       0.036242  0.292695  
DiabetesPedigreeFunction  0.033561  0.173844  
Age                       1.000000  0.238356  
Outcome                   0.238356  1.000000

In [53]:
# 상관관계가 제일 낮은 요소 제거 -> 결과값 확인해보니 예측이 더 떨어짐.. 그래서 주석처리
#del diabetes['BloodPressure']
#diabetes

In [54]:
data = X = diabetes.iloc[:,:-1].values
data

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [55]:
data.shape

(768, 8)

In [56]:
label = y = diabetes.iloc[:,-1]
label.values

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,

In [57]:
X_train, X_test, y_train, y_test = train_test_split(data, label,  test_size=0.2, random_state=11)

In [64]:
# normalize
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_s = scaler.transform(X_train)
X_train_s

array([[0.76470588, 0.53266332, 0.57377049, ..., 0.57575758, 0.07109208,
        0.51666667],
       [0.05882353, 0.39698492, 0.6147541 , ..., 0.53872054, 0.13319058,
        0.01666667],
       [0.29411765, 0.65326633, 0.67213115, ..., 0.65824916, 0.37301927,
        0.26666667],
       ...,
       [0.23529412, 0.61809045, 0.6557377 , ..., 0.53872054, 0.15331906,
        0.21666667],
       [0.17647059, 0.5678392 , 0.36065574, ..., 0.37710438, 0.0235546 ,
        0.01666667],
       [0.11764706, 0.64824121, 0.        , ..., 0.64814815, 0.09379015,
        0.33333333]])

In [65]:
scaler = MinMaxScaler()
scaler.fit(X_test)
X_test_s = scaler.transform(X_test)
X_test_s

array([[0.13333333, 0.40909091, 0.54545455, ..., 0.41281669, 0.13078347,
        0.07843137],
       [0.06666667, 0.65656566, 0.63636364, ..., 0.38599106, 0.24305984,
        0.01960784],
       [0.        , 0.54040404, 0.54545455, ..., 0.39344262, 0.03392967,
        0.03921569],
       ...,
       [0.        , 0.50505051, 0.8       , ..., 0.69746647, 0.54534238,
        0.19607843],
       [0.33333333, 0.39393939, 0.43636364, ..., 0.50223547, 0.35533621,
        0.07843137],
       [0.26666667, 0.67676768, 0.65454545, ..., 0.35469449, 0.12276373,
        0.76470588]])

In [67]:
# 결과값이 1개 - sigmoid / 하나 이상은 softmax
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])

In [68]:
# 4. 모델 컴파일
model.compile(optimizer = 'adam', loss='binary_crossentropy', metrics=['accuracy'])

In [69]:
# X_test, y_test 결과값이 나와야함
history = model.fit(X_train_s, y_train, 
                    validation_data=(X_test_s,y_test), 
                    steps_per_epoch = 30, 
                    validation_steps=50,
                    epochs=30, verbose=1)

Epoch 1/30
30/30 [==============================] - 1s 15ms/step - loss: 0.6556 - accuracy: 0.6384 - val_loss: 0.6429 - val_accuracy: 0.6494
Epoch 2/30
30/30 [==============================] - 0s 6ms/step - loss: 0.6145 - accuracy: 0.6661
Epoch 3/30
30/30 [==============================] - 0s 4ms/step - loss: 0.5659 - accuracy: 0.7150
Epoch 4/30
30/30 [==============================] - 0s 4ms/step - loss: 0.5303 - accuracy: 0.7231
Epoch 5/30
30/30 [==============================] - 0s 4ms/step - loss: 0.5005 - accuracy: 0.7508
Epoch 6/30
30/30 [==============================] - 0s 4ms/step - loss: 0.5274 - accuracy: 0.7557
Epoch 7/30
30/30 [==============================] - 0s 5ms/step - loss: 0.4892 - accuracy: 0.7769
Epoch 8/30
30/30 [==============================] - 0s 6ms/step - loss: 0.4701 - accuracy: 0.7818
Epoch 9/30
30/30 [==============================] - 0s 5ms/step - loss: 0.4620 - accuracy: 0.7785
Epoch 10/30
30/30 [==============================] - 0s 4ms/step - loss: 0.

In [70]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_5 (Flatten)         (None, 8)                 0         
                                                                 
 dense_20 (Dense)            (None, 256)               2304      
                                                                 
 dense_21 (Dense)            (None, 128)               32896     
                                                                 
 dense_22 (Dense)            (None, 64)                8256      
                                                                 
 dense_23 (Dense)            (None, 1)                 65        
                                                                 
Total params: 43,521
Trainable params: 43,521
Non-trainable params: 0
_________________________________________________________________


In [71]:
score = model.evaluate(X_train_s, y_train, verbose=1)
print('정답률 = ', score[1],'loss=', score[0])

20/20 [==============================] - 0s 2ms/step - loss: 0.3843 - accuracy: 0.8257
정답률 =  0.8257328867912292 loss= 0.3843015134334564
